### ISSUE TITLE
Windows Task Scheduler doesn't process config.ps1

### ISSUE THREAD

**Issue by LasoGit** [kmwoley/restic-windows-backup#53] opened 2021-09-23 11:31 UTC
EDIT: see last post

Dear Kevin,

many thanks for your work! 
I followed your installation instructions successfully until defining $BackupSources in config.ps1.

This will back up C:\ entirely:
> $BackupSources = @{}
> $BackupSources["C:\"] = @(
> #    'Users'
> )

I only want to include a specific folder and can't manage to replace the **# 'Users'** line with **C:\path\to\folder**
Can you please advise? Sorry for raising this as an issue, I searched the forum to no avail and think this is the best place to look for an answer...

**Comment by rawtaz** [comment] 2021-09-23 12:13
@LasoGit You have to explain the problem. What do you mean by "can't manage to replace the # 'Users' line"? It's just a line of text - replace it using a text editor?

**Comment by LasoGit** [comment] 2021-09-23 14:22
@rawtaz Sorry for not explaining the issue concisely.
Following the instructions, I successfully initialized a new repo (step 4 ii.) so assume I did everything right up to that point.
In step 5, I changed the default $BackupSources in order to only backup "folder123" and not the entire drive C:\. 
I replaced lines 27-30 in config.ps1 with this:
> $BackupSources = @{}
> $BackupSources["C:\"] = @(
> users\user\path\to\folder123
> )
I omitted step 6 (nothing to exclude), followed step 7 (exclusion from win detection) and finally triggered the task manually in Task Scheduler.
In the Task Scheduler, "Restic Backup" shows as "running", but nothing happens except for empty error logs appearing in <script directory>/logs.
According to the forum, this script is well tested and thus should work unless I made a mistake. Since the repo was initialized successfully, I assume I edited secrets.ps1 correctly. In order to rule out an error in the email configuration, I changed line 24 in config.ps1 to $SendEmailOnError = $false.
So I suspect that I used a wrong notation to set $BackupSources to a single folder.

**Comment by LasoGit** [comment] 2021-09-23 14:24
@rawtaz Sorry for not explaining the issue concisely.
Following the instructions, I successfully initialized a new repo (step 4 ii.) so assume I did everything right up to that point.
In step 5, I changed the default $BackupSources in order to only backup "folder123" and not the entire drive C:.
I replaced lines 27-30 in config.ps1 with this:

$BackupSources = @{}
$BackupSources["C:\"] = @(
users\user\path\to\folder123
)

I omitted step 6 (nothing to exclude), followed step 7 (exclusion from win detection) and finally triggered the task manually in Task Scheduler.
In the Task Scheduler, "Restic Backup" shows as "running", but nothing happens except for empty error logs appearing in <script directory>/logs.
According to the forum, this script is well tested and thus should work unless I made a mistake. Since the repo was initialized successfully, I assume I edited secrets.ps1 correctly. In order to rule out an error in the email configuration, I changed line 24 in config.ps1 to $SendEmailOnError = $false.
So I suspect that I used a wrong notation to set $BackupSources to a single folder.

**Comment by rawtaz** [comment] 2021-09-23 14:25
Is it possible that you're simply missing the single quotes around that path? I mean, the line should probably read `'users\user\path\to\folder123'` and not `users\user\path\to\folder123`, considering the `'Users'` you had there before was quoted (and also that it makes sense from a programming/scripting language perspective that the string needs to be quoted). Please try that and see if it helps.

Restic initializes a repository without having to deal with the backup paths you specify here, so they have no relation at all.

**Comment by kmwoley** [comment] 2021-09-23 16:22
PowerShell can sometimes delay the output into the .log and .err files;
it's a bit annoying. It's possible it's running just fine, but not dumping
to the logs.
One way you can test is to just run the `.\backup.ps1` script from an
elevated PowerShell prompt and see if it runs and then completes.
One way I check to see if a backup is running is by looking at the target
repository files and confirm that (1) the lockfile keeps getting updated
(usually every ten min) and (2) more files continue to get added to the
repository.
You can find the lockfile in the `<repository>\locks` folder. If there's no
lockfile there, then there's no backup running. If there's a lockfile, look
at the date - it should keep getting updated if a backup is running.
 Another thing to test is a very small folder, just to confirm it backs up
and runs for a very small data set.
HTH

**Comment by BillBardon** [comment] 2021-09-23 16:56
I'm not new to restic, but this is my first reply to the list.

Have you tried using a complete path, starting from the root? 

The users I backup in Windows have their folders defined as 

"C:\Users\*\Desktop C:\Users\*\Documents C:\Users\*\Downloads C:\Users\*\Pictures"

In your case it would be

'C:\users\user\path\to\folder123'


Bill Bardon
COMPUTASSIST, LLC
Omaha, Nebraska

**Comment by LasoGit** [comment] 2021-09-23 17:08
@kmwoley Thanks for the response! I ran the `.\backup.ps1` script from PowerShell and it worked fine, taking about 2 minutes in total. 👍 
I waited over an hour for Task Manager to finish, so the problem seems to be with Task Manager - I checked the _Restic Backup_ task's properties and found these arguments: 
`-ExecutionPolicy Bypass -NonInteractive -NoLogo -NoProfile -Command ".\backup.ps1; exit $LASTEXITCODE"`
These seem to be all default values - I double checked by running the whole script installation again. 
Do you have any other idea what may cause this issue?

**Comment by LasoGit** [comment] 2021-09-23 17:11
@BillBardon Thanks for the response! The path I put in last `'users\user\path\to\folder123'` works fine with the script itself, the problem seems to be with Windows Task Scheduler (see my response above).

**Comment by kmwoley** [comment] 2021-09-23 17:28
@lasogit - Those run arguments look right to me. Try running Task Scheduler
again and see what happens. Try right-clicking and selecting "End", and
then "Run" and see what happens.

**Comment by LasoGit** [comment] 2021-09-23 18:05
@kmwoley I did that several times to no avail, also running Task Scheduler with elevated privileges.
Just to be sure I rebooted my system and found no differences:
- running `.\backup.ps1` directly from PowerShell works fine, takes about 2 mins and writes a xxx.log.txt
- manually starting the task in Task Scheduler just triggers 4 events [right click > properties > history] within 1 second:

![events](https://user-images.githubusercontent.com/62600910/134559281-4810a752-085e-42a4-b6cf-d8f403981f4a.jpg)
_Sorry for posting a screenshot with german text - they translate roughly to "129 - process for scheduled(?) task", "100 - task has been started", "200 - action has been started", "110 - action was triggered by user"._

20 minutes later, I find no changes in the repository and no new events in Task Scheduler.

**Comment by kmwoley** [comment] 2021-11-15 04:09
@LasoGit - did you ever get this sorted out. I do wonder if there's an issue caused by localization somehow. Unfortunately I don't know what more I can do to help you out. If you found a solution, please post it here.

**Comment by LasoGit** [comment] 2021-11-15 13:51
@kmwoley I couldn't solve the issue so I decided to write my own (much simpler) script in Bash (I'm using Ubuntu/WSL2 on Windows 10) and start the bash script via Task Scheduler automatically which works fine.
Sorry for not updating the issue, thanks for asking!

**Comment by kmwoley** [comment] 2023-01-15 05:05
Closing this issue out given it's age and status.

**Closed by kmwoley** 2023-01-15 05:05 UTC
